"""Tests for optimize_hippo_storage and the optimize_lance_storage deprecation shim.

Covers:
- Report dict contains records/edges/events keys with required sub-keys.
- VACUUM actually runs and can reduce DB file size after deletes.
- hnswlib index is rebuilt when optimize runs.
- PRAGMA wal_checkpoint(TRUNCATE) is issued BEFORE VACUUM.
- Never raises on per-table errors (error captured in report dict).
- optimize_lance_storage alias emits DeprecationWarning and routes correctly.

All tests use pytest's ``tmp_path`` fixture — no ~/.iai-mcp/ touched.
"""
from __future__ import annotations

import warnings
from pathlib import Path
from uuid import uuid4

import numpy as np
import pytest

from iai_mcp.hippo import HippoDB
from iai_mcp.types import EMBED_DIM


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_store(tmp_path: Path):
    """Return a minimal store-shaped object backed by a real HippoDB."""

    class _Store:
        def __init__(self, db: HippoDB) -> None:
            self.db = db

    return _Store(HippoDB(tmp_path))


def _random_row(tier: str = "episodic") -> dict:
    """Return a minimal records-table row dict."""
    return {
        "id": str(uuid4()),
        "tier": tier,
        "literal_surface": "hello world",
        "embedding": np.random.rand(EMBED_DIM).astype(np.float32).tolist(),
        "created_at": "2026-01-01T00:00:00+00:00",
    }


# ---------------------------------------------------------------------------
# Test 1: report contains all three tables with required keys
# ---------------------------------------------------------------------------


def test_optimize_returns_report_for_all_tables(tmp_path: Path) -> None:
    """optimize_hippo_storage returns a dict with records/edges/events keys."""
    from iai_mcp.maintenance import optimize_hippo_storage

    store = _make_store(tmp_path)
    report = optimize_hippo_storage(store)

    assert isinstance(report, dict)
    for table in ("records", "edges", "events"):
        assert table in report, f"missing table {table!r} in report"
        sub = report[table]
        assert "rows_before" in sub
        assert "rows_after" in sub
        assert "size_bytes_before" in sub
        assert "size_bytes_after" in sub
        assert "elapsed_sec" in sub
        # No error expected on a fresh empty store.
        assert "error" not in sub, f"unexpected error on {table}: {sub.get('error')}"


# ---------------------------------------------------------------------------
# Test 2: VACUUM runs and size reporting works
# ---------------------------------------------------------------------------


def test_vacuum_actually_runs(tmp_path: Path) -> None:
    """VACUUM runs without error; size_bytes_after is reported (may be 0 on empty store)."""
    from iai_mcp.maintenance import optimize_hippo_storage

    store = _make_store(tmp_path)
    # Insert and delete rows to create fragmentation VACUUM can reclaim.
    tbl = store.db.open_table("records")
    rows = [_random_row() for _ in range(5)]
    tbl.add(rows)
    for r in rows:
        tbl.delete(f"id = '{r['id']}'")

    report = optimize_hippo_storage(store)

    assert "error" not in report["records"], report["records"].get("error")
    # size_bytes_after is an int (may be 0 on very small db, that's fine).
    assert isinstance(report["records"]["size_bytes_after"], int)
    assert report["records"]["elapsed_sec"] >= 0.0


# ---------------------------------------------------------------------------
# Test 3: hnswlib index rebuilt during optimize
# ---------------------------------------------------------------------------


def test_hnswlib_index_rebuilt_during_optimize(tmp_path: Path) -> None:
    """optimize_hippo_storage triggers hnswlib rebuild; index file exists after."""
    from iai_mcp.maintenance import optimize_hippo_storage

    store = _make_store(tmp_path)
    # Insert a record so there's something in the index.
    tbl = store.db.open_table("records")
    tbl.add([_random_row()])

    # Remove the hnsw file to simulate corruption / missing snapshot.
    hnsw_path: Path = store.db._hippo_dir / "records.hnsw"
    if hnsw_path.exists():
        hnsw_path.unlink()

    report = optimize_hippo_storage(store)

    # No error from hnsw rebuild.
    assert "error" not in report["records"], report["records"].get("error")
    # After optimize, index file should be present (rebuild + save).
    assert hnsw_path.exists(), "records.hnsw should be regenerated by optimize"
    # Verify the saved file loads cleanly.
    import hnswlib
    idx = hnswlib.Index(space="cosine", dim=EMBED_DIM)
    idx.load_index(str(hnsw_path), max_elements=1000)
    assert idx.get_current_count() >= 1


# ---------------------------------------------------------------------------
# Test 4: wal_checkpoint called BEFORE VACUUM
# ---------------------------------------------------------------------------


def test_wal_checkpoint_called_before_vacuum(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """PRAGMA wal_checkpoint(TRUNCATE) is issued before VACUUM in the same execute sequence."""
    from iai_mcp.maintenance import optimize_hippo_storage

    store = _make_store(tmp_path)
    call_log: list[str] = []

    # sqlite3.Connection.execute is a read-only C attribute and cannot be
    # replaced via monkeypatch. Instead, wrap the entire _conn with a proxy
    # that delegates all attribute access to the real connection while
    # intercepting execute() calls to log checkpoint vs VACUUM ordering.
    real_conn = store.db._conn

    class _LoggingProxy:
        def execute(self, sql: str, *args, **kwargs):
            sql_upper = sql.strip().upper()
            if "WAL_CHECKPOINT" in sql_upper:
                call_log.append("checkpoint")
            elif sql_upper == "VACUUM":
                call_log.append("vacuum")
            return real_conn.execute(sql, *args, **kwargs)

        def __getattr__(self, name: str):
            return getattr(real_conn, name)

    monkeypatch.setattr(store.db, "_conn", _LoggingProxy())

    optimize_hippo_storage(store)

    assert "checkpoint" in call_log, "wal_checkpoint was not called"
    assert "vacuum" in call_log, "VACUUM was not called"
    cp_idx = call_log.index("checkpoint")
    vac_idx = call_log.index("vacuum")
    assert cp_idx < vac_idx, (
        f"wal_checkpoint (pos {cp_idx}) must come before VACUUM (pos {vac_idx})"
    )


# ---------------------------------------------------------------------------
# Test 5: never raises on per-table error
# ---------------------------------------------------------------------------


def test_never_raises_on_per_table_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """optimize_hippo_storage captures per-step errors in the report; does not raise."""
    from iai_mcp.maintenance import optimize_hippo_storage

    store = _make_store(tmp_path)
    real_conn = store.db._conn

    # Same proxy pattern as test 4 — sqlite3.Connection.execute is read-only.
    class _VacuumErrorProxy:
        def execute(self, sql: str, *args, **kwargs):
            if sql.strip().upper() == "VACUUM":
                raise ValueError("simulated VACUUM failure")
            return real_conn.execute(sql, *args, **kwargs)

        def __getattr__(self, name: str):
            return getattr(real_conn, name)

    monkeypatch.setattr(store.db, "_conn", _VacuumErrorProxy())

    # Must not raise.
    report = optimize_hippo_storage(store)

    assert isinstance(report, dict)
    # At least one table should carry the error.
    errors = [sub["error"] for sub in report.values() if "error" in sub]
    assert errors, "expected at least one error entry in report after VACUUM failure"
    assert any("simulated VACUUM failure" in e for e in errors)


# ---------------------------------------------------------------------------
# Test 6: optimize_lance_storage deprecation alias
# ---------------------------------------------------------------------------


def test_optimize_lance_storage_deprecation_alias(tmp_path: Path) -> None:
    """optimize_lance_storage emits DeprecationWarning and routes to optimize_hippo_storage."""
    from iai_mcp.maintenance import optimize_lance_storage

    store = _make_store(tmp_path)

    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        result = optimize_lance_storage(store)

    dep_warnings = [w for w in caught if issubclass(w.category, DeprecationWarning)]
    assert dep_warnings, "optimize_lance_storage must emit DeprecationWarning"
    assert "optimize_lance_storage" in str(dep_warnings[0].message).lower() or \
           "deprecated" in str(dep_warnings[0].message).lower()

    # Return value must be the full report dict (same as optimize_hippo_storage).
    assert isinstance(result, dict)
    for table in ("records", "edges", "events"):
        assert table in result
